"""Async-safe request/job correlation context for structured logging (Roadmap PR15A).

Reuses the request_id/correlation_id already generated by app.main's
request_context_middleware (Roadmap PR3) -- this module does not create a
second ID mechanism, it only makes the existing IDs available to log calls
made anywhere in a request's async call chain (service/CRUD layer code
that has no direct access to the Request object) without threading them
through every function signature.

contextvars.ContextVar, not a thread-local or a global: a thread-local
would leak or cross-contaminate between concurrently-scheduled requests
that happen to share the same OS thread under asyncio's cooperative
concurrency. asyncio.Task creation copies the current context, so a value
set here before `await`ing further work remains correctly scoped to that
task's call chain.

Background jobs (app.worker.scheduler) use job_run_id_var, a distinct
variable from request_id_var/correlation_id_var -- a scheduled job run is
not an HTTP request and must not be mislabeled as one.
"""

import contextvars
import logging

request_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar("request_id", default=None)
correlation_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar("correlation_id", default=None)
job_run_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar("job_run_id", default=None)


class RequestContextFilter(logging.Filter):
    """Attaches the current request/correlation/job-run IDs (if any) to every LogRecord.

    Runs for every record passed to the handler this filter is attached
    to, regardless of which logger emitted it -- this is what lets
    service/CRUD-layer log calls automatically carry the current request's
    IDs without each call site reading the ContextVars itself. Outside any
    request or job context (e.g. a log line emitted at application
    startup), all three attributes are None and the JSON formatter omits
    them rather than emitting null noise.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        # Only fills in a value the call site didn't already provide via
        # `extra={...}` -- Starlette's ServerErrorMiddleware (which invokes
        # the catch-all `Exception` handler) sits *outside*
        # request_context_middleware, so it runs after that middleware's
        # `finally` block has already reset the ContextVars for a genuinely
        # unhandled exception. That handler passes request_id/correlation_id
        # explicitly (read from request.state, which isn't reset) instead
        # of relying on the ambient ContextVar for that one path; every
        # other log call keeps using the ambient value set here.
        if not hasattr(record, "request_id"):
            record.request_id = request_id_var.get()
        if not hasattr(record, "correlation_id"):
            record.correlation_id = correlation_id_var.get()
        if not hasattr(record, "job_run_id"):
            record.job_run_id = job_run_id_var.get()
        return True
